### ISSUE TITLE
Platform don't found

### ISSUE THREAD

**Issue by mickexman** [fermartv/emt_madrid#2]
Hola!

Thank you in first place.
I've been trying to install and use the integration but not success for me.
I followed the steps, but just after validate the code I get the message:

Platform error sensor.emt_madrid - Integration 'emt_madrid' not found.

I don't know what to do, don't know what I'm doing wrong 🤷🏻‍♂️

**Comment by fermartv** [comment]
Thanks for the feedback! This issue should be solved with the last release. Please update your version to the last one.

Let me know if there is any other issue :)

**Comment by mickexman** [comment]
Works perfect now.

Gracias!!!!
