### ISSUE TITLE
Stops 4490 and 4491 no sensor

### ISSUE THREAD

**Issue by txespirito** [fermartv/emt_madrid#5]
No sensor generation in this stops (other stops no problem)

- platform: emt_madrid
  email: !secret emt_user
  password: !secret emt_pass
  stop: 4490
  lines:
    -  "172"
    -  "172SF"
  icon: "mdi:bus-clock"

- platform: emt_madrid
  email: !secret emt_user
  password: !secret emt_pass
  stop: 4491
  lines:
    -  "172"
    -  "172SF"
  icon: "mdi:bus-clock"

**Comment by fermartv** [comment]
Hola! (if you prefer english let me know)

Parece que la propia API de la EMT da error con esas paradas. Por lo que he podido comprobar pasa con las paradas de 4 dígitos como las que has pasado.
{
    "code": "81",
    "description": "No records found or error, (lapsed: 300 millsecs)",
    "datetime": "2023-07-14T17:09:53.871537",
    "data": [
        {}
    ]
}

Me he puesto en contacto con ellos para reportar el problema y ver si hay algún método alternativo para estos casos, ya que la documentación que tienen no lo mencionan.

Actualizaré este issue si me responden o si encuentro otra alternativa.

Gracias por el aviso!

**Comment by txespirito** [comment]
Gracias Fernando,
de todas maneras si solo pongo la 172 (y quito la 172SF) tampoco genera el sensor, No se si afectará a lineas concretas o tambien a lo que indicas de los 4 digitos.
Un saludo

**Comment by fermartv** [comment]
He estado investigando más y es un problema con ciertas paradas (no depende del número de dígitos de la parada ni de la línea que pase por ellas). Me da la sensación de que la EMT ha actualizado a medias su base de datos y que le faltan algunas paradas.

Las buenas noticias es que he encontrado un método alternativo para obtener datos de esas paradas. En unos días hago los cambios y publicaré nueva versión. 

Por si tienes curiosidad, este es el endpoint que falla con algunas paradas: https://apidocs.emtmadrid.es/#api-Block_3_TRANSPORT_BUSEMTMAD-detail_of_stop

Y este otro parece que funciona: https://apidocs.emtmadrid.es/#api-Block_3_TRANSPORT_BUSEMTMAD-detail_of_stops_arround_stops

Lo malo de este segundo es que no da tanta información sobre las líneas (faltan las frecuencias y hora de servicio).

**Comment by txespirito** [comment]
Muchas gracias Fernando. Eres un crack

**Comment by fermartv** [comment]
Al final me he liado y he hecho un apaño...
Prueba a actualizar con lo de esta rama: https://github.com/fermartv/emt_madrid/tree/dev

![imagen](https://github.com/fermartv/emt_madrid/assets/20268311/2116f525-1377-47a4-a0cb-d8f8ffbe9b66)
![imagen](https://github.com/fermartv/emt_madrid/assets/20268311/56fe3fcc-26cc-4636-8fb6-829d7a847621)

Si todo va bien, añado unos tests, hago refactor y saco una nueva versión.

**Comment by txespirito** [comment]
Funciona perfectamente, me reitero en que eres un crack.

**Comment by txespirito** [comment]
Hola FErnando,
otra vez vuelven a NO aparecer lineas :(

**Comment by danielramfer** [comment]
Hola chicos,

Antes de nada, Fer, quería agradecerte el trabajazo, llevo mucho tiempo con este invento funcionando y siendo super util.
Pero es cierto que ultimamente viene fallando, puede ser por las ultimas actualizaciones de home assistant???

Actualmente los sensores no están visibles en home assistant y solo algua que otra vez si aparecen correctamente...

**Comment by mmoracantallops** [comment]
Me uno a la cuestión porque me pasa lo mismo, no están apareciendo los sensores - pero es que creo que la API también está dando problemas. Espero que me podáis confirmar si esto es así, muchas gracias!

**Comment by txespirito** [comment]
Buenas noches,
¿sabeis si la integración sigue activa? hace tiempo que no me aparecen los sensores y no se si es culpa mia o no.
Gracias

**Comment by fermartv** [comment]
Qué errores os aparece en los logs?

**Comment by txespirito** [comment]
No consigo sacar los log de este complemento, pero por ejemplo las paradas 4490 y 4491 no me generan sensor

**Comment by fermartv** [comment]
A mi sí que me están funcionando
![imagen](https://github.com/user-attachments/assets/26a5a45f-1a3f-4519-a5a2-bb2e57e0a040)

```sensor:
  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stop: 4490
    lines:
      - "172"
      - "172SF"
    icon: "mdi:image-filter-hdr-outline"

  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stop: 4491
    lines:
      - "172"
      - "172SF"
    icon: "mdi:fountain"

**Comment by txespirito** [comment]
# "EMT 172_Casa->Telefonica"
- platform: emt_madrid
  email: !secret emt_user
  password: !secret emt_pass
  stop: 4490
  lines:
    -  "172"
    -  "172SF"
  icon: "mdi:bus-clock"

# "EMT 172_Casa->Sanchinarro"
- platform: emt_madrid
  email: !secret emt_user
  password: !secret emt_pass
  stop: 4491
  lines:
    -  "172"
    -  "172SF"
  icon: "mdi:bus-clock"

No se, lo tengo igual y el resto de paradas funciona.
Tengo actualizado el repositorio de HACS, es muy raro

**Comment by fermartv** [comment]
HACS no estaba soportado y por lo tanto no estaban mostrándose los últimos cambios. He generado una nueva release y con eso ya aparece en HACS la última versión (2.0.1) que debería corregir este problema.
