### ISSUE TITLE
Can't find the sensor in Home Assistant

### ISSUE THREAD

**Issue by serghidalg** [fermartv/emt_madrid#6]
Hey there!

I followed your guide installing the sensor but it  does not seem to work. 
I did a git clone of your https://github.com/fermartv/emt_madrid/tree/master/custom_components/emt_madrid files and put them in my custom_components emt folder as shown below.
![ls_emt](https://github.com/fermartv/emt_madrid/assets/79108691/c8b6a48a-4368-4186-985e-9da9d4f1d840)
After that, I tuned my configuration.yaml file to have the sensor like so:  (also note that for testing purposes, I didnt add my password and email as !secret BLABLABLA but just as "BLABLABLA". Not sure if this may be affecting the result.)
![cat_config](https://github.com/fermartv/emt_madrid/assets/79108691/50cde6c8-c6c4-4275-828b-2ca0518f62bd)
I restarted home assistant and... nothing ?

I am missing anything? Is this project not working at the moment?
Thanks!!

**Comment by fermartv** [comment]
Is there anything in your Home Assistant logs? Whay version and installation method of Home Assistant are you running?
