### ISSUE TITLE
Sensor not appearing in HA - API issues too?

### ISSUE THREAD

**Issue by mmoracantallops** [fermartv/emt_madrid#7]
Hi,

First of all, thank you for your work. I was going to try a similar integration but I found yours, so it makes no sense to make another one. However, I installed it via HACS, all seems fine, but the sensor is not appearing in HA (I followed your instructions). I see this is also happening to others, so it might be a HA thing. In any case, I'm also trying with the API manually and I keep getting error 500 in the time arrival bus endpoint (some other endpoints give weird errors and a few others seem to work). I'm using bus stop 1569 with line 3. Do you know whether the API is giving this kind of issues lately? I tried to contact mobility labs but I'm only getting silence as their response. 

En cualquier caso, muchas gracias y a ver si conseguimos que funcione,

**Comment by frentemorao** [comment]
Comentar que yo sí he conseguido que funcione aunque me aparece directamente como entidad.
Me falta probar lo del segundo bus

**Comment by fermartv** [comment]
Es posible que se hubiese caído el servidor de la EMT. A mí me funciona con la siguiente configuración:

```sensor:
  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stop: 1569
    lines:
      - "3"```

Creo que la API de EMT no tiene mantenimiento. No he conseguido que me respondan a ninguna de las preguntas que les he hecho :(
